# Generated by Django 3.0.5 on 2020-04-17 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0002_agent_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.expressions.Case, related_name='agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agent',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, related_name='agent', to='agent.Agent'),
        ),
        migrations.AddField(
            model_name='agent',
            name='top_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subagent', to='agent.Agent'),
        ),
    ]
