# Generated by Django 3.0.5 on 2020-04-23 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_center_profile'),
        ('agent', '0003_auto_20200423_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='center',
        ),
        migrations.AddField(
            model_name='agent',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='center.Center'),
            preserve_default=False,
        ),
    ]
