# Generated by Django 3.0.5 on 2020-04-23 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_room', '0002_auto_20200423_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secound_phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='شماره تلفن وارد شده در فرمت صحیح نمیباشد فرمت صحیح به این صورت میباشد 9123456789 لطفا ضمن اصلاح شماره تلفن مجداد تلاش کنید', regex='^9\\+?1?\\d{9}$')])),
                ('lessons', models.ManyToManyField(related_name='teacher', to='class_room.Lesson')),
            ],
            options={
                'verbose_name': 'Teacher',
            },
        ),
    ]
