# Generated by Django 3.0.4 on 2020-03-31 00:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=20, null=True)),
                ('father_phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن وارد شده در فرمت صحیح نمیباشد فرمت صحیح به این صورت میباشد 9123456789 لطفا ضمن اصلاح شماره تلفن مجداد تلاش کنید', regex='^\\+?1?\\d{10}$')])),
                ('field', models.CharField(choices=[('riazi', 'riazi'), ('tajrobi', 'tajrobi'), ('ensani', 'ensani'), ('other', 'other')], max_length=7)),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2)),
                ('birth_certificate', models.ImageField(blank=True, null=True, upload_to='student_profile')),
            ],
            options={
                'verbose_name': 'Student',
            },
        ),
    ]
