# Generated by Django 3.0.5 on 2020-04-23 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=20, null=True)),
                ('father_phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن وارد شده در فرمت صحیح نمیباشد فرمت صحیح به این صورت میباشد 9123456789 لطفا ضمن اصلاح شماره تلفن مجداد تلاش کنید', regex='^9\\+?1?\\d{9}$')])),
                ('field', models.CharField(choices=[('riazi', 'ریاضی فیزیک'), ('tajrobi', 'علوم تجربی'), ('ensani', 'علوم انسانی'), ('other', 'سایر')], max_length=7)),
                ('level', models.CharField(choices=[('1', 'یکم ابتدايی'), ('2', ' دوم ابتدايی'), ('3', 'سوم ابتدايی'), ('4', 'چهارم ابتدايی'), ('5', 'پنجم ابتدايی'), ('6', 'ششم ابتدايی'), ('7', 'یکم دبیرستان'), ('8', ' دوم دبیرستان'), ('9', 'سوم دبیرستان'), ('10', 'چهارم دبیرستان'), ('11', 'پنجم دبیرستان'), ('12', 'ششم دبیرستان')], max_length=2)),
                ('birth_certificate', models.ImageField(blank=True, null=True, upload_to='student_birth_certificate')),
            ],
            options={
                'verbose_name': 'Student',
            },
        ),
    ]
