# Generated by Django 3.0.4 on 2020-03-31 00:38

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.BigIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='کد ملی ارسال شده صحیح نمیباشد کد مالی باید 10 رقم باشد لطفا مجددا تلاش کنید', regex='^\\+?1?\\d{10}$')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_profile')),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='شماره تلفن وارد شده در فرمت صحیح نمیباشد فرمت صحیح به این صورت میباشد 9123456789 لطفا ضمن اصلاح شماره تلفن مجداد تلاش کنید', regex='^\\+?1?\\d{10}$')])),
                ('user_type', models.CharField(choices=[('teacher', 'teacher'), ('student', 'student'), ('agent', 'agent'), ('center', 'center')], max_length=7)),
                ('city', models.CharField(choices=[('azerbayjan_sh', 'azerbayjan_sh'), ('azerbayjan_gh', 'azerbayjan_gh'), ('ardabil', 'ardabil'), ('isfehan', 'isfehan'), ('alborz', 'alborz'), ('ilam', 'ilam'), ('bushehr', 'bushehr'), ('tehran', 'tehran'), ('charmahal', 'charmahal'), ('khorasan_j', 'khorasan_j'), ('khorasan_r', 'khorasan_r'), ('khorasan_s', 'khorasan_s'), ('khuzestan', 'khuzestan'), ('zanjan', 'zanjan'), ('semnan', 'semnan'), ('sistan', 'sistan'), ('fars', 'fars'), ('ghzvin', 'ghzvin'), ('ghom', 'ghom'), ('kurdistan', 'kurdistan'), ('kerman', 'kerman'), ('kermanshah', 'kermanshah'), ('kuhkiloie', 'kuhkiloie'), ('golestan', 'golestan'), ('gilan', 'gilan'), ('lurestan', 'lurestan'), ('mazandaran', 'mazandaran'), ('markazi', 'markazi'), ('hurmuzgan', 'hurmuzgan'), ('hamedan', 'hamedan'), ('yazd', 'yazd')], max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Profile',
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
