# Generated by Django 3.0.4 on 2020-03-31 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='کد ملی ارسال شده صحیح نمیباشد کد مالی باید 10 رقم باشد لطفا مجددا تلاش کنید', regex='^\\+?1?\\d{10}$')]),
        ),
    ]
