# Generated by Django 3.0.5 on 2020-04-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'معلم'), ('student', 'دانش آموز'), ('agent', 'نماینده'), ('center', 'دفتر مرکزی')], max_length=7),
        ),
    ]
